# 1. Register DID using seed in VON web UI
# 2. Start Cloudagent with seed (updates endpoint automatically)

### Get anton's connections
GET http://localhost:8021/connections
Accept: application/json

### Get bob's connections
GET http://localhost:8031/connections
Accept: application/json

### anton: Create invitation
# state: => invitation
POST http://localhost:8021/out-of-band/create-invitation
Content-Type: application/json

{
  "handshake_protocols": ["https://didcomm.org/didexchange/1.1"],
  "use_public_did": true
}

> {%
    client.global.set("invitation", JSON.stringify(response.body.invitation));
    client.global.set("invitation_id", response.body.invitation["@id"]);
    client.global.set("invitation_msg_id", response.body.invi_msg_id);
    client.global.set("invitation_url", response.body.invitation_url);
    client.global.set("did_anton", response.body.invitation.services[0]);
%}

### anton: Get connection id
GET http://localhost:8021/connections?invitation_msg_id={{invitation_msg_id}}

> {% client.global.set("conn_id_anton", response.body.results[0].connection_id); %}

### Generate QR code
GET https://api.qrserver.com/v1/create-qr-code/?data={{invitation_url}}
Accept: image/png

### bob: Receive invitation
POST http://localhost:8031/out-of-band/receive-invitation
Content-Type: application/json

{{invitation}}

> {% client.global.set("conn_id_bob", response.body.connection_id); %}

### bob: Accept invitation
# state: invitation => request
#POST http://localhost:8031/didexchange/{{conn_id_bob}}/accept-invitation?use_did=A77DF4w5TbCnPFwhJkTTd1
POST http://localhost:8031/didexchange/5c75ffe5-2ec1-40c9-ac2a-20fe08f9e3c8/accept-invitation?use_did=98sHhNwPHQCjaEhYEn9szz
Content-Type: application/json

### anton: Accept connection
# state: request => response => ... => active
#POST http://localhost:8021/didexchange/{{conn_id_anton}}/accept-request?use_public_did=true
POST http://localhost:8021/didexchange/f19029ca-bd8d-4678-a80b-9789a22da7b5/accept-request?use_public_did=true
Content-Type: application/json

### anton: Send message
# state: request => response => ... => active
POST http://localhost:8021/connections/{{conn_id_anton}}/send-message
Content-Type: application/json

{
  "content": "Hallo bob"
}



### Delete anton's connection
DELETE http://localhost:8021/connections/{{conn_id_anton}}
Accept: application/json

### Delete bob's connection
DELETE http://localhost:8031/connections/{{conn_id_bob}}
Accept: application/json
