%%{init: {
  "theme": "neutral",
  "themeVariables": {
    "xactorTextColor": "#C40D20",
    "signalColor": "#C40D20",
    "xsignalTextColor": "#C40D20",
    "activationBorderColor": "#C40D20"
  }
}}%%
sequenceDiagram
    participant car as Car
    participant truck as Truck
    participant discovery as Discovery
    participant indy as Indy Node

    Note over car,indy: Truck offers Service

    discovery-->>truck: Broadcast DIDComm Invitation
    activate truck
    opt Establish Connection
        truck->>discovery: 
        discovery->>truck: 
        truck->>discovery: 
    end

    truck->>+discovery: Register FRONT_CAMERA_STREAM service
    discovery->>discovery: Create Entry

    loop Establish Trust
        discovery->>truck: Request Credentials
        truck-->>discovery: Present Credentials
        discovery->>+indy: Verify Credential
        indy-->>-discovery: 
        discovery->>discovery: Update Entry
    end
    deactivate discovery
    deactivate truck


    Note over car,indy: Car accesses Service

    discovery-->>car: Broadcast DIDComm Invitation
    activate car
    opt Establish Connection
        car->>discovery: 
        discovery->>car: 
        car->>discovery: 
    end


    car->>+discovery: Query available services
    discovery-->>-car: 

    opt Establish Connection
        car->>truck: 
        truck->>car: 
        car->>truck: 
    end

    car->>+truck: Request Video Stream

    loop Establish Trust
        truck->>car: Request Credential
        car-->>truck: Present Credential
        truck->>+indy: Verify Credential
        indy-->>-truck: 
    end

    truck->>-car: Send Stream Manifest

    loop
        car->>+truck: Request Video Chunk
        truck->>-car: Send Video Chunk
    end

    deactivate car
