%%{init: {
  "theme": "neutral",
  "themeVariables": {
    "xactorTextColor": "#C40D20",
    "signalColor": "#C40D20",
    "xsignalTextColor": "#C40D20",
    "activationBorderColor": "#C40D20"
  }
}}%%
sequenceDiagram
    participant controller as Controller
    participant alice as ACA-py Agent
    participant bob as Other Agent
%%    participant indy as Indy Node
    
    controller->>alice: Connect to DID
    activate controller
    
%%    opt diddoc not cached
%%        alice->>indy: retrieve did document
%%        indy-->>alice: 
%%    end

    autonumber 1
    alice->>bob: didexchange request
    autonumber 1
    bob->>alice: didexchange response
    alice->>bob: didexchange complete
    autonumber off
    
    alice-->>controller: Completed Webhook
    deactivate controller
