sequenceDiagram
    participant controller as Controller
    participant alice as ACA-py Agent
    participant bob as Other Agent
%%    participant indy as Indy Node

    activate controller
    par 100 times
        controller->>alice: Request Proof
        alice->>bob: present-proof request-presentation
        bob->>alice: present-proof presentation
        alice->>bob: present-proof ack

%%        opt material not cached
%%            alice->>indy: retrieve verification material
%%            indy-->>alice: 
%%        end

        alice->>alice: verify presentation
        

    alice-->>controller: Done Webhook
    end
    
    deactivate controller
