sequenceDiagram
    participant controller as Controller
    participant alice as ACA-py Agent
    participant bob as Other Agent
%%    participant indy as Indy Node

    controller->>alice: Request Proof
    activate controller

    autonumber 1
    alice->>bob: present-proof request-presentation
    autonumber 1
    bob->>alice: present-proof presentation
    alice->>bob: present-proof ack
    autonumber off

%%    opt material not cached
%%        alice->>indy: retrieve verification material
%%        indy-->>alice: 
%%    end

    alice->>alice: verify presentation

    alice-->>controller: Done Webhook
    deactivate controller
