%%{init: {
  "theme": "neutral",
  "themeVariables": {
    "xactorTextColor": "#C40D20",
    "signalColor": "#C40D20",
    "xsignalTextColor": "#C40D20",
    "activationBorderColor": "#C40D20"
  }
}}%%
sequenceDiagram
    participant controller as MPV (DASH client)
    participant alice as ACA-py Agent
    participant bob as Other Agent
    
    activate controller
    
    loop
        controller->>alice: Request DASH segment
        
        alice->>bob: videostreaming chunk-request
        bob->>alice: videostreaming chunk-response
        
        alice-->>controller: DASH segment
    end
    
    deactivate controller
