name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - acapy-plugins/**
      - agents/**
      - wallets/**
      - Dockerfile

  workflow_dispatch:
    inputs:
      platforms:
        description: 'Platforms - Comma separated list of the platforms to support.'
        required: true
        default: linux/amd64,linux/arm64
        type: string
  workflow_call:
    inputs:
      platforms:
        required: true
        default: linux/amd64,linux/arm64
        type: string

env:
  PLATFORMS: ${{ inputs.platforms || 'linux/amd64,linux/arm64' }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and Push Image to ghcr.io
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/antoncuranz/didcomm-on-quic/agents:latest
          platforms: ${{ env.PLATFORMS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
#      - name: Build and Push Image to ghcr.io (no-diddoc-cache)
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          push: true
#          tags: ghcr.io/antoncuranz/didcomm-on-quic/agents:no-diddoc-cache
#          platforms: ${{ env.PLATFORMS }}
#          cache-from: type=gha
#          cache-to: type=gha,mode=max
#          build-args: |
#            DISABLE_DIDDOC_CACHE=true
